// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUxymTCR-CEajbNelFgGErOUU-ER3ctZU',
    appId: '1:75670352059:web:fa4432f8bcdad78019b99e',
    messagingSenderId: '75670352059',
    projectId: 'voterseye',
    authDomain: 'voterseye.firebaseapp.com',
    storageBucket: 'voterseye.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICrW1HRQFY9qZDC_i5kVIr7reiuHsNIg',
    appId: '1:75670352059:android:cebe82440fa426a719b99e',
    messagingSenderId: '75670352059',
    projectId: 'voterseye',
    storageBucket: 'voterseye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSh57Jjs845g_tHhmqH08E1_b2D5rq1ps',
    appId: '1:75670352059:ios:c69de5da0941248a19b99e',
    messagingSenderId: '75670352059',
    projectId: 'voterseye',
    storageBucket: 'voterseye.firebasestorage.app',
    iosBundleId: 'org.reclaimprotocol.voterseye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSh57Jjs845g_tHhmqH08E1_b2D5rq1ps',
    appId: '1:75670352059:ios:c69de5da0941248a19b99e',
    messagingSenderId: '75670352059',
    projectId: 'voterseye',
    storageBucket: 'voterseye.firebasestorage.app',
    iosBundleId: 'org.reclaimprotocol.voterseye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUxymTCR-CEajbNelFgGErOUU-ER3ctZU',
    appId: '1:75670352059:web:7d568910b37fac1d19b99e',
    messagingSenderId: '75670352059',
    projectId: 'voterseye',
    authDomain: 'voterseye.firebaseapp.com',
    storageBucket: 'voterseye.firebasestorage.app',
  );

}